FROM busybox:1

MAINTAINER "Jasper Lievisse Adriaanse" <jasper@redcoolbeans.com>
LABEL com.baculasystems.bacula.version="7.2.0" \
      com.redcoolbeans.image.version="1.0.0"

VOLUME /var/lib/postgresql/data
